# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

name: Secrets detector

on:
  pull_request:

jobs:
  # If necessary, rebuild the secrets baseline:
  # detect-secrets scan --exclude-files \
  #   'pyproject\.toml|\.github/workflows/config/\.secrets\.baseline|tests/test_utils/recipes/*' > \
  #   .github/workflows/config/.secrets.baseline
  secrets-detector:
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_secrets-detector.yml@v0.70.0
